# Generated by Django 4.1 on 2022-09-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_owner_alter_book_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="owner",),
    ]
